[package]
name = "jiman"
version = "0.1.1"
edition = "2024"

[dependencies]
clap = { version = "4.5.37", features = ["derive", "string"] }
clap_complete = { version = "4.5.48", features = ["unstable-dynamic"] }
term_size = "0.3.2"
